### ISSUE TITLE
Problem with pre-commit auto update

### ISSUE THREAD

**Issue by justvanrossum** [googlefonts/fontra-glyphs#25]
I merged #23, and ran it manually. The run failed like this:

https://github.com/googlefonts/fontra-glyphs/actions/runs/8016379275/workflow

I'm not sure I understand. The updated black may have caused a file to be reformatted, which somehow prevents the rest of the action to run. This feels a bit like chicken and egg.

@fabiocaccamo, can you investigate? In the worst case I'll have to do a manual update of the pre-commit dependencies first, but that feels like it's defeating the purpose.

**Comment by fabiocaccamo** [comment]
> I'm not sure I understand. The updated black may have caused a file to be reformatted, which somehow prevents the rest of the action to run. This feels a bit like chicken and egg.

@justvanrossum yes, it's exactly what happened: `1 file reformatted, 2 files left unchanged.`

If we want the PR to pass the tests, we must run `pre-commit run --all` and commit also the re-formatted files, the risk is only that if many files are re-formatted, the PR becomes very big and all other branches in progress should be rebased.

**Comment by justvanrossum** [comment]
But the *creation* of the PR should not fail, even if the PR run (once submitted) will fail. That's what's confusing: why does the creation of the PR fail? It's not giving helpful information.

**Comment by fabiocaccamo** [comment]
I run `pre-commit run --all` locally, but the strange thing is that no file has been reformatted.

**Comment by justvanrossum** [comment]
> the strange thing is that no file has been reformatted 

In this repo, with updated pre-commit dependencies?

If I run 

    black --diff src

with black 24.2.0, I get this:

```diff
(testing) JvR-M3:fontra-glyphs just$ black --diff src/
--- /Users/just/code/git/BlackFoundry/fontra-glyphs/src/fontra_glyphs/backend.py	2024-02-27 09:55:07.015060+00:00
+++ /Users/just/code/git/BlackFoundry/fontra-glyphs/src/fontra_glyphs/backend.py	2024-02-27 09:56:46.829839+00:00
@@ -238,13 +238,15 @@
             for axis, value in zip(self.axes, gsLayer._brace_coordinates())
         )
 
     def _getSmartLocation(self, gsLayer, localAxesByName):
         location = {
-            name: localAxesByName[name].minValue
-            if poleValue == Pole.MIN
-            else localAxesByName[name].maxValue
+            name: (
+                localAxesByName[name].minValue
+                if poleValue == Pole.MIN
+                else localAxesByName[name].maxValue
+            )
             for name, poleValue in gsLayer.smartComponentPoleMapping.items()
         }
         return {
             disambiguateLocalAxisName(name, self.axisNames): value
             for name, value in location.items()
@@ -344,12 +346,14 @@
     basePoleMapping = gsGlyph.layers[0].smartComponentPoleMapping
     return [
         LocalAxis(
             name=axis.name,
             minValue=axis.bottomValue,
-            defaultValue=axis.bottomValue
-            if basePoleMapping[axis.name] == Pole.MIN
-            else axis.topValue,
+            defaultValue=(
+                axis.bottomValue
+                if basePoleMapping[axis.name] == Pole.MIN
+                else axis.topValue
+            ),
             maxValue=axis.topValue,
         )
         for axis in gsGlyph.smartComponentAxes
     ]
would reformat /Users/just/code/git/BlackFoundry/fontra-glyphs/src/fontra_glyphs/backend.py

All done! ✨ 🍰 ✨
1 file would be reformatted, 1 file would be left unchanged.
```

**Comment by justvanrossum** [comment]
This does not happen with black 23.1.0, so I think this is exactly the problem.

**Comment by justvanrossum** [comment]
@fabiocaccamo, do you have an idea how to move forward with this?

**Comment by fabiocaccamo** [comment]
@justvanrossum I'll work on it again this week.

**Comment by fabiocaccamo** [comment]
@justvanrossum check https://github.com/googlefonts/fontra-glyphs/pull/27 (I can't assign you as reviewer here).
